server:
  port: 8080

spring:  
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productos
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/productos/**, /v1/api-docs/producto, /doc/swagger-ui.html
        - id: inventario
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/inventario/**, /v1/api-docs/producto, /doc/swagger-ui.html
        - id: usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/usuarios/**, /v1/api-docs/producto, /doc/swagger-ui.html
        - id: mensajes
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/mensajes/**, /v1/api-docs/producto, /doc/swagger-ui.html