server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: productos
          uri: http://localhost:8081
          predicates:
            - Path=/api/productos/**
        - id: usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuarios/**
