spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      
      routes:
        # ========== RUTAS DE MICROSERVICIOS ==========
        - id: productos
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/productos/**

        - id: inventario
          uri: http://localhost:8081
          predicates:
            - Path=/api/v2/inventario/**

        - id: usuarios
          uri: http://localhost:8082
          predicates:
            - Path=/api/v2/usuarios/**

        - id: mensajes
          uri: http://localhost:8083
          predicates:
            - Path=/api/v2/mensajes/**

        # ========== SWAGGER MENSAJES ==========
        # Ruta para Swagger UI recursos (DEBE ir ANTES que swagger-ui.html)
        - id: swagger-mensajes-ui-resources
          uri: http://localhost:8083
          predicates:
            - Path=/mensajes/swagger-ui/**
          filters:
            - RewritePath=/mensajes/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        # Ruta principal de Swagger UI (redirección directa al index)
        - id: swagger-mensajes-ui-main
          uri: http://localhost:8083
          predicates:
            - Path=/mensajes/swagger-ui.html
          filters:
            - RewritePath=/mensajes/swagger-ui.html, /swagger-ui/index.html

        # Ruta alternativa para acceso directo al index
        - id: swagger-mensajes-ui-index
          uri: http://localhost:8083
          predicates:
            - Path=/mensajes/swagger-ui/index.html
          filters:
            - RewritePath=/mensajes/swagger-ui/index.html, /swagger-ui/index.html

        # API Docs principal
        - id: swagger-mensajes-docs-main
          uri: http://localhost:8083
          predicates:
            - Path=/mensajes/v3/api-docs
          filters:
            - RewritePath=/mensajes/v3/api-docs, /v3/api-docs

        # API Docs con parámetros
        - id: swagger-mensajes-docs-sub
          uri: http://localhost:8083
          predicates:
            - Path=/mensajes/v3/api-docs/**
          filters:
            - RewritePath=/mensajes/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}

        # ========== SWAGGER OTROS MICROSERVICIOS ==========
        # Productos
        - id: swagger-productos-ui-main
          uri: http://localhost:8081
          predicates:
            - Path=/productos/swagger-ui.html
          filters:
            - RewritePath=/productos/swagger-ui.html, /swagger-ui.html

        - id: swagger-productos-ui-resources
          uri: http://localhost:8081
          predicates:
            - Path=/productos/swagger-ui/**
          filters:
            - RewritePath=/productos/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        - id: swagger-productos-docs-main
          uri: http://localhost:8081
          predicates:
            - Path=/productos/v3/api-docs
          filters:
            - RewritePath=/productos/v3/api-docs, /v3/api-docs

        - id: swagger-productos-docs-sub
          uri: http://localhost:8081
          predicates:
            - Path=/productos/v3/api-docs/**
          filters:
            - RewritePath=/productos/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}

        # Usuarios
        - id: swagger-usuarios-ui-main
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/swagger-ui.html
          filters:
            - RewritePath=/usuarios/swagger-ui.html, /swagger-ui.html

        - id: swagger-usuarios-ui-resources
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/swagger-ui/**
          filters:
            - RewritePath=/usuarios/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        - id: swagger-usuarios-docs-main
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/v3/api-docs
          filters:
            - RewritePath=/usuarios/v3/api-docs, /v3/api-docs

        - id: swagger-usuarios-docs-sub
          uri: http://localhost:8082
          predicates:
            - Path=/usuarios/v3/api-docs/**
          filters:
            - RewritePath=/usuarios/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}